### ISSUE TITLE
Fallo al ejecutar los test e2e

### ISSUE THREAD

**Issue by migrodcab** [EGC1617Grupo/agora-gui-elections#24]
Al intentar ejecutar los test e2e referente a "dynamic-directive-webspec.js" me salta el siguiente error: 
Failures:

  1) Exception loading: /home/developer/egc/code/agora-gui-elections/test/dynamic-directive-webspec.js Error
   Message:
     SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
   Stacktrace:
     SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at require (internal/module.js:12:17)
    at Function.promise (/home/developer/egc/code/agora-gui-elections/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:650:9)

La versión que tengo instalada para las distintas herramientas son:
- grunt-cli v1.2.0
- grunt v0.4.5
- Protractor: Version 4.0.14
- webdriver-manager 10.3.0

**Comment by migrodcab** [comment]
Arreglado en el commit @266e20a71eb472ec66562c41bd4d19f58ba4a38b
Se solucionaba añadiendo la línea "use strict"
